import Head from "next/head";
import Link from "next/link";

export function HomeScreen() {
  return (
    <>
      <Head>
        <title>Linda Pagina Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World!</h1>
        <Link href={"/dashboard"}>Linda dashboard</Link>
      </main>
    </>
  );
}
